In [ ]:
# Classification problem solving using 3 Dense Artificial Neural Network layers, 
#              ReLU activation function, Adam optimizer, and sparse_categorical_crossentropy loss function
# Making an artificial dataset using random numbers and trying to classify the age groups of people
# From Krish Naik lectures

In [2]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras. optimizers import Adam
import numpy as np
from random import randint
from sklearn.preprocessing import MinMaxScaler

In [3]:
# Creating the training dataset randomly

train_sample = []
train_label = []
for i in range(1000):
    younger_ages = randint(13, 64)
    train_sample.append(younger_ages)
    train_label.append(0)
    
    older_ages = randint(65, 100)
    train_sample.append(older_ages)
    train_label.append(1)

In [16]:
train_sample[:5], train_label[:5]

([46, 85, 48, 89, 28], [0, 1, 0, 1, 0])

In [17]:
# Converting into numpy arrays
train_sample = np.array(train_sample)
train_label = np.array(train_label)

In [19]:
train_sample, train_label

(array([ 46,  85,  48, ..., 100,  36,  77]), array([0, 1, 0, ..., 1, 0, 1]))

In [23]:
# Scaling the data from 0 to 1
scaler = MinMaxScaler(feature_range=(0,1))
train_sample_scaled = scaler.fit_transform(train_sample.reshape(-1,1)) # Reshape the 1D array for keras model

In [25]:
train_sample_scaled[:5]

array([[0.37931034],
       [0.82758621],
       [0.40229885],
       [0.87356322],
       [0.17241379]])

In [26]:
model = Sequential([Dense(16,input_dim=1, activation='relu'),Dense(32, activation='relu'),Dense(2, activation='softmax')])

Instructions for updating:
Colocations handled automatically by placer.


In [27]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_2 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [28]:
model.compile(Adam(lr=0.001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [29]:
model.fit(train_sample_scaled, train_label, batch_size=10, epochs=10)

Epoch 1/10
2000/2000 [==============================] - 3s 1ms/step - loss: 0.5231 - accuracy: 0.7805
Epoch 2/10
2000/2000 [==============================] - 1s 575us/step - loss: 0.1839 - accuracy: 0.9755
Epoch 3/10
2000/2000 [==============================] - 1s 570us/step - loss: 0.0942 - accuracy: 0.9880
Epoch 4/10
2000/2000 [==============================] - 1s 508us/step - loss: 0.0675 - accuracy: 0.9900
Epoch 5/10
2000/2000 [==============================] - 1s 505us/step - loss: 0.0523 - accuracy: 0.9925
Epoch 6/10
2000/2000 [==============================] - 1s 518us/step - loss: 0.0446 - accuracy: 0.9945
Epoch 7/10
2000/2000 [==============================] - 1s 514us/step - loss: 0.0395 - accuracy: 0.9935
Epoch 8/10
2000/2000 [==============================] - 1s 515us/step - loss: 0.0349 - accuracy: 0.9930
Epoch 9/10
2000/2000 [==============================] - 1s 548us/step - loss: 0.0317 - accuracy: 0.9960
Epoch 10/10
2000/2000 [==============================] - 1s 505us/

In [31]:
# Creating the test sample randomly

test_sample = []
test_label = []
for i in range(500):
    younger_ages = randint(13, 64)
    test_sample.append(younger_ages)
    test_label.append(0)
    
    older_ages = randint(65, 100)
    test_sample.append(older_ages)
    test_label.append(1)

In [34]:
test_sample[:5], test_label[:5]

([47, 80, 43, 100, 54], [0, 1, 0, 1, 0])

In [36]:
# Converting into numpy arrays
test_sample = np.array(test_sample)
test_label = np.array(test_label)
test_sample[:5], test_label[:5]

(array([ 47,  80,  43, 100,  54]), array([0, 1, 0, 1, 0]))

In [37]:
# Scaling the data from 0 to 1
scaler = MinMaxScaler(feature_range=(0,1))
test_sample_scaled = scaler.fit_transform(test_sample.reshape(-1,1)) # Reshape the 1D array for keras model

In [38]:
test_sample_scaled[:5]

array([[0.3908046 ],
       [0.77011494],
       [0.34482759],
       [1.        ],
       [0.47126437]])

In [40]:
test_sample_scaled_preds = model.predict_classes(test_sample_scaled, batch_size=10)

In [41]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(test_label, test_sample_scaled_preds))
print(classification_report(test_label, test_sample_scaled_preds))
print(accuracy_score(test_label, test_sample_scaled_preds))

[[490  10]
 [  0 500]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       500
           1       0.98      1.00      0.99       500

    accuracy                           0.99      1000
   macro avg       0.99      0.99      0.99      1000
weighted avg       0.99      0.99      0.99      1000

0.99
